const auth = {
  brandName: "brandName",
  switchAuth: {
    login: "switchAuth.login",
    registration: "switchAuth.registration",
  },
  login: {
    email: "login.email",
    emailPlaceholder: "login.email.placeholder",
    password: "login.password",
    passwordPlaceholder: "login.password.placeholder",
    submit: "login.submit",
    rules: {
      emailRequired: "login.email.rule.required",
      emailValidate: "login.email.rule.validate",
      passwordRequired: "login.password.rule.required",
    },
  },
  registration: {
    lastName: "registration.lastName",
    lastNamePlaceholder: "registration.lastName.placeholder",
    firstName: "registration.firstName",
    firstNamePlaceholder: "registration.firstName.placeholder",
    middleName: "registration.middleName",
    middleNamePlaceholder: "registration.middleName.placeholder",
    photo: "registration.photo",
    photoDesc: "registration.photo.desc",
    phone: "registration.phone",
    phonePlaceholder: "registration.phone.placeholder",
    email: "registration.email",
    emailPlaceholder: "registration.email.placeholder",
    password: "registration.password",
    passwordPlaceholder: "registration.password.placeholder",
    institute: "registration.institute",
    institutePlaceholder: "registration.institute.placeholder",
    faculty: "registration.faculty",
    facultyPlaceholder: "registration.faculty.placeholder",
    subject: "registration.subject",
    subjectPlaceholder: "registration.subject.placeholder",
    submit: "registration.submit",
    rules: {
      emailRequired: "registration.email.rule.required",
      emailValidate: "registration.email.rule.validate",
      passwordRequired: "registration.password.rule.required",
      lastNameRequired: "registration.lastName.rule.required",
      firstNameRequired: "registration.firstName.rule.required",
      middleNameRequired: "registration.middleName.rule.required",
      photoRequired: "registration.photo.rule.required",
      phoneRequired: "registration.phone.rule.required",
      instituteRequired: "registration.institute.rule.required",
      facultyRequired: "registration.faculty.rule.required",
      subjectRequired: "registration.subject.rule.required",
    },
    successful: {
      title: "registration.successful.title",
      subTitle: "registration.successful.subtitle",
      login: "registration.successful.login",
      password: "registration.successful.password",
    },
  },
};

export default auth;
