export const FETCH_QUESTION_COUNT = "FETCH_QUESTION_COUNT";
export const SET_QUESTION_COUNT = "SET_QUESTION_COUNT";
export const SHOW_LOADING_QUESTION_COUNT = "SHOW_LOADING_QUESTION_COUNT";

export const SET_TEST_INFO_ID = "SET_TEST_INFO_ID";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const SHOW_LOADING_CREATE = "SHOW_LOADING_CREATE";
export const HIDE_LOADING_CREATE = "HIDE_LOADING_CREATE";

export const GET_QUESTION = "GET_QUESTION";
export const SET_QUESTION = "SET_QUESTION";
export const SHOW_LOADING_QUESTION = "SHOW_LOADING_QUESTION";
export const HIDE_LOADING_QUESTION = "HIDE_LOADING_QUESTION";

export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const FETCH_PREVIEW_QUESTIONS = "FETCH_PREVIEW_QUESTIONS";
export const SET_PREVIEW_QUESTIONS = "SET_PREVIEW_QUESTIONS";
export const SHOW_LOADING_PREVIEW_QUESTIONS = "SHOW_LOADING_PREVIEW_QUESTIONS";
export const HIDE_LOADING_PREVIEW_QUESTIONS = "HIDE_LOADING_PREVIEW_QUESTIONS";
